name: Build and Package Binary

on:
  push:
    paths:
      - 'main.py'

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pygame-ce

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --name lqlute-beta --add-data "data:data" main.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Windows-Qlute
        path: ./dist
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pygame-ce
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --name lqlute-beta --add-data "data:data" main.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Linux-Qlute
        path: ./dist
